# Generated by Django 5.2.8 on 2025-12-01 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('NEW', 'New Applicant'), ('REPLACEMENT', 'Replacement ID')], default='NEW', help_text='Type of application: New or Replacement.', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('COLLECTED', 'ID Collected')], default='PENDING', help_text='Current processing status.', max_length=15)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('passport_picture', models.FileField(help_text='Passport photograph upload.', upload_to='passports/')),
                ('county_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('subcounty_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('location_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('sublocation_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guardian_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('death_certificate_number', models.CharField(blank=True, help_text='Required if parents/guardian are deceased.', max_length=50, null=True)),
                ('old_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('police_abstract_form', models.FileField(blank=True, help_text='Scanned copy of the police abstract.', null=True, upload_to='abstracts/')),
                ('applicant', models.ForeignKey(help_text='The user who submitted this application.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID Application',
                'verbose_name_plural': 'ID Applications',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
