# Generated by Django 5.2.8 on 2025-12-03 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idapplication',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='idapplication',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='True if M-Pesa payment was successful.'),
        ),
        migrations.AddField(
            model_name='idapplication',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='M-Pesa Transaction ID', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='idapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idapplication',
            name='application_type',
            field=models.CharField(choices=[('NEW', 'New Applicant'), ('REPLACEMENT', 'Replacement ID')], default='NEW', max_length=15),
        ),
        migrations.AlterField(
            model_name='idapplication',
            name='death_certificate_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='idapplication',
            name='passport_picture',
            field=models.FileField(upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='idapplication',
            name='police_abstract_form',
            field=models.FileField(blank=True, null=True, upload_to='abstracts/'),
        ),
        migrations.AlterField(
            model_name='idapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined'), ('COLLECTED', 'ID Collected')], default='PENDING', max_length=15),
        ),
    ]
