# Generated by Django 5.2.8 on 2025-12-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_idapplication_amount_paid_idapplication_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idapplication',
            name='generated_id_number',
            field=models.CharField(blank=True, help_text='System generated National ID Number (8 digits)', max_length=20, null=True, unique=True),
        ),
    ]
