# Generated by Django 5.2.8 on 2025-12-01 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Reviewer', help_text='The administrative role (e.g., Senior Approver, Data Entry).', max_length=100)),
                ('department', models.CharField(default='National Registration', help_text='The department the administrator belongs to.', max_length=100)),
                ('is_senior_reviewer', models.BooleanField(default=False, help_text='Designates if this admin can finalize application approval/rejection.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrator Profile',
                'verbose_name_plural': 'Administrator Profiles',
            },
        ),
    ]
