from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from .forms import NewApplicantForm, ReplacementIDForm
from .models import IDApplication
from .auth_forms import CustomUserCreationForm, CustomAuthenticationForm
from .mpesa import trigger_stk_push, generate_simulated_transaction_code


# ... (Authentication views remain unchanged) ...
def user_signin(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('user_dashboard')
    else:
        form = CustomAuthenticationForm()
    return render(request, 'Users/signin.html', {'form': form})


def user_signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('user_dashboard')
    else:
        form = CustomUserCreationForm()
    return render(request, 'Users/signup.html', {'form': form})


def user_signout(request):
    logout(request)
    return redirect('user_signin')


# --- Dashboard View ---

def user_dashboard(request):
    if not request.user.is_authenticated:
        return redirect('user_signin')

    current_user = request.user

    # 1. Existing App Check
    new_app_exists = IDApplication.objects.filter(applicant=current_user, application_type='NEW').exists()

    # 2. Get Valid ID Record (if exists)
    # This retrieves the original APPROVED application that holds the generated ID number
    valid_id_record = IDApplication.objects.filter(
        applicant=current_user,
        application_type='NEW',
        status__in=['APPROVED', 'COLLECTED']
    ).first()

    has_valid_id = valid_id_record is not None

    if request.method == 'POST':
        if 'new_submit' in request.POST:
            form_type = 'NEW'
            form = NewApplicantForm(request.POST, request.FILES)
        elif 'replace_submit' in request.POST:
            form_type = 'REPLACEMENT'
            form = ReplacementIDForm(request.POST, request.FILES)
        else:
            form_type = None
            form = None

        if form and form.is_valid():
            # RULE 1: Cannot apply for NEW if one exists
            if form_type == 'NEW' and new_app_exists:
                form.add_error(None, "You already have a New ID Application on file.")

            # RULE 2: Cannot apply for REPLACEMENT if no valid ID exists
            elif form_type == 'REPLACEMENT' and not has_valid_id:
                form.add_error(None, "Eligibility Error: You don't have an approved ID to replace.")

            else:
                # Prepare object
                application = form.save(commit=False)
                application.applicant = current_user
                application.application_type = form_type

                # --- NEW LOGIC: VALIDATE ID NUMBER ---
                if form_type == 'REPLACEMENT':
                    entered_id = form.cleaned_data.get('old_id_number')

                    # Check if entered ID matches the one generated by the system
                    if valid_id_record and entered_id != valid_id_record.generated_id_number:
                        form.add_error('old_id_number',
                                       f"ID Number mismatch. Our records show your ID is {valid_id_record.generated_id_number}.")

                        # Re-render with error
                        application_history = IDApplication.objects.filter(applicant=current_user).order_by(
                            '-date_submitted')
                        context = {
                            'current_user': current_user.username,
                            'application_status': application_history.first().get_status_display() if application_history.exists() else 'No Application Submitted',
                            'application_history': application_history,
                            'new_app_exists': new_app_exists,
                            'has_valid_id': has_valid_id,
                            'new_form': NewApplicantForm(),
                            'replace_form': form,
                        }
                        return render(request, 'Users/dashboard.html', context)

                    # --- M-PESA LOGIC ---
                    mpesa_number = form.cleaned_data.get('mpesa_payment_number')
                    amount = 1.00
                    success, msg, req_id = trigger_stk_push(mpesa_number, amount)

                    if success:
                        application.is_paid = True
                        application.amount_paid = amount
                        application.mpesa_code = generate_simulated_transaction_code()
                    else:
                        form.add_error(None, f"Payment Failed: {msg}")
                        # Re-render context on error... (same logic as above)
                        return render(request, 'Users/dashboard.html',
                                      {'replace_form': form, 'current_user': current_user.username,
                                       'new_form': NewApplicantForm(), 'has_valid_id': has_valid_id,
                                       'application_history': IDApplication.objects.filter(applicant=current_user),
                                       'new_app_exists': new_app_exists})

                application.save()
                return redirect('user_dashboard')

    else:
        new_form = NewApplicantForm()
        replace_form = ReplacementIDForm()

    application_history = IDApplication.objects.filter(applicant=current_user).order_by('-date_submitted')

    context = {
        'current_user': current_user.username,
        'application_status': application_history.first().get_status_display() if application_history.exists() else 'No Application Submitted',
        'application_history': application_history,
        'new_app_exists': new_app_exists,
        'has_valid_id': has_valid_id,
        'new_form': new_form,
        'replace_form': replace_form,
    }
    return render(request, 'Users/dashboard.html', context)


def app_detail(request, app_id):
    if not request.user.is_authenticated:
        return redirect('user_signin')

    current_user = request.user
    application = get_object_or_404(IDApplication, pk=app_id)

    if application.applicant != current_user and not current_user.is_staff:
        return redirect('user_dashboard')

    if current_user.is_staff:
        base_template = 'Admins/base.html'
    else:
        base_template = 'Users/base.html'

    context = {
        'application': application,
        'base_template': base_template,
    }
    return render(request, 'Users/app_detail.html', context)